Add bookings
k-mesavage/java-shareit pull request #2
Opened 2023-09-05 15:30 UTC by k-mesavage

2023-09-06 13:16 UTC, AnastasiyaFomkina requested changes

2023-09-06 13:16 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    BookingService service;
Не хватает модификатора доступа  + final

2023-09-06 13:16 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    public Long id;
В коммерческой разработке принято максимально скрывать все поля класса, чтобы сделать программу безопасной и избежать множественных багов.

В редких случаях поля класса могут иметь модификатор доступа 
* `protected` - если данные поля будут как-либо переопределяться наследниками
* `public`- если поле считается константой и используется по всему проекту

2023-09-06 13:16 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/dto/ShortBookingDto.java
> +    Long bookerId;
Нужно добавить полям модификаторы доступа

2023-09-06 13:16 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    public LocalDateTime end;
Лучше добавить [@JsonFormat](https://www.baeldung.com/spring-boot-formatting-json-dates) для полей с датой, так мы можем избежать множественных ошибок при парсинге даты из json

2023-09-06 13:16 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/dto/WorkingBookingDto.java
> +@Data
Можно заменить `@Data` на [@Value](https://urvanov.ru/2015/09/19/lombok-value-%D0%BB%D1%91%D0%B3%D0%BA%D0%BE%D0%B5-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BD%D0%B5%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D1%8F%D0%B5%D0%BC%D1%8B%D1%85-%D0%BA%D0%BB/), тогда все dto объекты будут максимально защищены от изменений, так как `@Value` генерирует неизменяемые приватные поля

2023-09-06 13:16 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>  @Data
Использование `@Data` в jpa-сущностях приводит к [вот этой проблеме](https://habr.com/ru/company/haulmont/blog/564682/)

Нужно удалить аннотацию из всех jpa-сущностей

2023-09-06 13:16 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (status.equals(ALL)) {
_Задание со "*"_
Данный блок кода можно оптимизировать с помощью паттерна проектирования 
[Цепочка обязанностей](https://refactoring.guru/ru/design-patterns/chain-of-responsibility) (сайт может не открываться без vpn).
Предлагаю изучить этот паттерн и попробовать реализовать его.

В коммерческой разработке очень часто используются паттерны проектирования, так как код становится более чистым и структурированным. А еще его становится проще поддерживать и масштабировать. 

А еще их часто спрашивают на собеседованиях 😉

2023-09-06 13:16 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (status.equals(ALL)) {
И здесь тоже пригодится цепочка обязанностей

2023-09-06 13:16 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dto/ShortItemDto.java
> +    public Long id;
Поправь, пожалуйста, во всех dto-объектах модификаторы доступа на `private`

2023-09-06 13:16 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/mapper/CommentMapper.java
> +@Data
А здесь зачем `@Data`?

2023-09-06 13:16 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +@Transactional
Вот [отличная статья ](https://habr.com/ru/companies/otus/articles/649093/) про использование транзакций. Лучше убрать лишние аннотации над методами, либо настроить аннотацию над классом и в нужных местах ее переопределять

2023-09-06 13:16 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (itemDto.getName() != null && !itemDto.getName().isBlank()) {
Обновление полей лучше вынести в маппер, так как перекладывание значений из одного поля в другое это его ответственность

2023-09-06 13:16 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/dto/ShortUserDto.java
> +public class ShortUserDto {
А это точно dto?

2023-09-06 13:16 UTC, AnastasiyaFomkina commented on src/main/resources/schema.sql
_Опционально_
Предлагаю попробовать добавить [индексы](https://tproger.ru/articles/indeksy-v-postgresql/), чтобы ускорить поиск

2023-09-07 00:25 UTC, k-mesavage commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    HandleGetterForOwner getterForOwner = new GetRejectedForOwner(new GetWaitingForOwner(new GetFutureForOwner(new GetPastForOwner(new GetAllForOwner(new GetCurrentForOwner(null))))));
Доброго времени! Не могу понять почему выводятся не все объекты? Вообще, на сколько целесообразно заводить цепочку ответственности на этом этапе проектирования, ведь не требуется проваливаться на частных?

2023-09-07 11:40 UTC, AnastasiyaFomkina requested changes

2023-09-07 11:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    HandleGetterForOwner getterForOwner = new GetRejectedForOwner(new GetWaitingForOwner(new GetFutureForOwner(new GetPastForOwner(new GetAllForOwner(new GetCurrentForOwner(null))))));
Цепочку обязанностей объективно писать в любом случае, так как она делает код расширяемым и чистым. 

Давай ее для начала максимально оптимизируем и посмотрим исправится ли проблема.

Для начала все классы должны быть в отдельный файлах. Один большой файл с кучей файлов - признах code smell, его практически нереально читать и сложно поддерживать. Нужно выделить отдельную директорию для хранения обработчиков - пусть она будет называться `handler`

Далее нужно создать один абстрактный класс, который будет заниматься обработкой логики всей цепочки, пусть он будет называться `BookingStateHandler`.
Внутри нужно определить все нужные нам для работы объекты:
`public BookingStateHandler next;` - ссылка на следующее звено цепочки
`public final BookingStorage repository;` - репозиторий
`public final BookingMapper mapper;` - маппер

Чтобы максимально обобщить метод обработки, нужно добавить два абстрактных метода:
1) `public abstract BookingState getState();` - в котором в каждом из обработчиков мы будем возвращать нужный нам стейт. Например, для `GetCurrent` - `BookingState.CURRENT`

2) `public abstract List<BookingDto> getBookings(long senderId);` - в котором мы будем возвращать список бронирований. Например, для `GetCurrent` - 

```
repository.findAllByBookerIdAndStartBeforeAndEndAfterOrderByStartDesc(senderId,
                LocalDateTime.now(),
                LocalDateTime.now()).stream()
            .map(mapper::toDto)
            .collect(Collectors.toList());
```

Для того, чтобы связать все обработчики в одну цепочку, в абстрактном классе нужно добавить статический метод:

```
public static BookingStateHandler link(BookingStateHandler handler, BookingStateHandler... handlerNext) {
        BookingStateHandler head = handler;
        for (BookingStateHandler item : handlerNext) {
            head.next = item;
            head = item;
        }
        return handler;
    }
```

с его помощью будет удобно связывать нужные нам хэндлеры - для двух методов нужно будет использовать разные цепочки. Например, для метода `getAllItemsBookingByOwner`:

```
BookingStateHandler handlers = BookingStateHandler.link(
            new GetRejectedForOwner(repository, mapper),
            new GetWaitingForOwner(repository, mapper),
            new GetFutureForOwner(repository, mapper),
            new GetPastForOwner(repository, mapper),
            new GetAllForOwner(repository, mapper),
            new GetCurrentForOwner(repository, mapper));
```

Ну и в самом конце нужно определить один общий метод `public List<BookingDto> handle(long senderId, BookingState state)`в котором должна быть общая логика обработки:

```
    public List<BookingDto> handle(long senderId, BookingState state) {
        if (state.equals(getState())) { // проверяем, что данный обработчик может найти информацию по данному стейту
            return getBookings(senderId); // возвращаем бронирования
        }
        if (next == null) { // если больше обработчиков не осталось - возвращаем пустой список
            return new ArrayList<>();
        }
        return next.handle(senderId, state); // переходим к следующему обработчику
    }
```

Если какие-то моменты будут не понятны, приходи в пачку, попробую объяснить еще более детально

2023-09-07 11:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    @JsonFormat
Нужно определить корректный паттерн для парсинга, как указано в [статье](https://www.baeldung.com/spring-boot-formatting-json-dates)

2023-09-07 11:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private LocalDateTime start;
Для поля `start` тоже полезно будет добавить `@JsonFormat`

2023-09-07 11:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/dto/WorkingBookingDto.java
> +    LocalDateTime start;
И в этом dto для полей со временем полезно будет добавить `@JsonFormat`

2023-09-07 11:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (itemDto.getName() != null && !itemDto.getName().isBlank()) {
Обновление полей лучше вынести в маппер, так как перекладывание значений из одного поля в другое это его ответственность

2023-09-07 11:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/dto/ShortUserDto.java
> +public class ShortUserDto {
А это точно dto?

2023-09-07 11:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    public Long getId() {
Все геттеры и сеттеры, нужно заменить на `@Getter` и `@Setter` от `lombok` во всем проекте

2023-09-08 18:55 UTC, AnastasiyaFomkina approved these changes

2023-09-09 11:50 UTC, merged