Add item requests
k-mesavage/java-shareit pull request #3
Opened 2023-09-21 10:03 UTC by k-mesavage

2023-09-24 14:34 UTC, AnastasiyaFomkina requested changes
Нужно заменить интеграционные тесты репозиториев приложения на тесты с использованием аннотации [@DataJpaTest](https://howtodoinjava.com/spring-boot2/testing/datajpatest-annotation/), как указано в тз
Можно еще немного подекомпозировать тесты и разбить из на логические составляющие. Это можно сделать с помощью [@Nested классов](https://www.petrikainulainen.net/programming/testing/junit-5-tutorial-writing-nested-tests/). Так код станет более читаемым и его будет проще поддерживать

2023-09-24 14:34 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        if (requestPage != null) {
Эта проверка лишняя, так как при запросе findAll мы не получим элемент`page == null`

2023-09-24 14:34 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                .collect(Collectors.toList());
Все строки выше можно заменить на один стрим:
```suggestion
                List<ItemRequestDto> created = itemRequestStorage.findAll(PageRequest
                .of(from, size, Sort.by("created").descending())).stream()
            .map(requestMapper::toItemRequestDto)
            .filter(i -> !i.getRequesterId().equals(userId))
            .collect(Collectors.toList());
```

2023-09-24 14:34 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    private static final String HEADER = "X-Sharer-User-Id";
Лучше использовать уже готовую константу `X_SHARER_USER_ID`, а не создавать везде новую

2023-09-24 14:34 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>      public List<ItemDto> searchItems(@RequestParam String text) {
Нужно добавить пангинацию

2023-09-24 14:34 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>      public List<ItemDto> getOwnerItems(@RequestHeader(X_SHARER_USER_ID) Long userId) {
Нужно добавить пангинацию

2023-09-24 14:34 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    void getAllItemsBookingByOwner() {
Нужно дописать тест

2023-09-25 06:17 UTC, k-mesavage commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    void getAllItemsBookingByOwner() {
Произвел слияние методов, этот метод отсутствует

2023-09-26 17:19 UTC, AnastasiyaFomkina requested changes
Нужно добавить `@DataJpaTest` тесты для всех репозиториев проекта

2023-09-28 15:22 UTC, AnastasiyaFomkina approved these changes

2023-10-03 07:36 UTC, merged