Add docker
k-mesavage/java-shareit pull request #4
Opened 2023-10-06 20:41 UTC by k-mesavage

2023-10-07 22:59 UTC, AnastasiyaFomkina requested changes
Отличная работа, молодец 🔥

2023-10-07 22:59 UTC, AnastasiyaFomkina commented on gateway/pom.xml
> +            <artifactId>spring-boot-starter-test</artifactId>
Так как в данном модуле нет тестов, данную зависимость нужно удалить

2023-10-07 22:59 UTC, AnastasiyaFomkina commented on server/pom.xml
> +			<artifactId>spring-boot-starter-validation</artifactId>
Эту зависимость нужно удалить из модуля server, больше не должно быть валидации входных данных, так как мы делегировали данную работу модулю gateway

2023-10-08 09:04 UTC, k-mesavage commented on server/pom.xml
> +			<artifactId>spring-boot-starter-validation</artifactId>
Это не возможно, exceptionHandler крутится на сервере

2023-10-08 14:24 UTC, AnastasiyaFomkina approved these changes

2023-10-08 17:35 UTC, merged